# スクレイピングで学校データを取得します。

In [9]:
import re
import time
import traceback
from pathlib import Path
from urllib.request import urlopen

import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from tqdm import tqdm
from webdriver_manager.chrome import ChromeDriverManager

# 東進のデータ
## 各情報取得用のURLを抽出する

```Python
https://www.toshin-hensachi.com/?line=2&university_type={ここに大学タイプ}&page={ここにページ}&sort=deviation&direction=DESC
```

In [13]:
data_list = []
for index,university_type in tqdm(enumerate([11,12,13,21,22,23])):
    for page in range(1,[12,1,13,15,1,9][index] +1):
        #^ __init__
        score =0
        url = f"https://www.toshin-hensachi.com/?line=2&university_type={university_type}&page={page}&sort=deviation&direction=DESC"
        print(url)
        a_url_list = [] #~大学詳細ページのURLを格納するリスト
        html = urlopen(url).read()  #^ スクレイピング
        time.sleep(1)  # 1秒待つ
        soup = BeautifulSoup(html, "html.parser")
        table = soup.find_all("table",class_="table-ranking")
        t_body= table[0].find("tbody")
        tr_list = t_body.find_all("tr")
        for tr in tr_list:
            try:
                #^ 偏差値
                td_score = tr.find("td",class_="td-score")
                if td_score is not None:
                    score = td_score.text.strip()
                    td_score = score
                else:
                    td_score = score
                #^ 大学情報
                td_info = tr.find("td", class_="td-info")
                try:
                    school_name_data = td_info.find("p", class_="school-name")
                except:
                    continue
                school_link = school_name_data.find("a")
                if school_name_data:
                    a_tag = school_name_data.find("a",href=True)
                    if a_tag is not None:
                        univ_url = a_tag.get("href")
                    school_name_tag = school_name_data.find("span", class_="school-name-university")
                    if school_name_tag:
                        school_name = school_name_tag.text.strip()
                        department = school_name_data.text.replace(school_name, "").strip()
                    else:
                        department = "学部情報なし"
                else:
                    school_name = "学校情報なし"
                    department = "学部情報なし"
                magnification_urls = td_info.find_all("a",class_="link-pasttest")
                for a in magnification_urls:
                    text = a.get_text(strip=True)
                    if text=="倍率を見る":
                        #^ 倍率を見る
                        magnification_url = a.get("href")
                experience_urls = td_info.find_all("a",class_="link-experience")
                for a in experience_urls:
                    if a.text.strip()=="合格体験記を見る":
                        #^ 合格体験記
                        SuccessfulExperience = a.get("href")
                    if a.text.strip()=="入試日程を見る":
                        #^ 入試日程
                        EntranceExamSchedule = a.get("href")
                dict= {"大学名":school_name,
                    "学部":department,
                    "大学詳細ページ":univ_url,
                    "偏差値": td_score,
                    "倍率情報": magnification_url,
                    "合格体験記": SuccessfulExperience,
                    "入試日程": EntranceExamSchedule,
                    }
                data_list.append(dict)
            except Exception as e:
                print("Error",tr)
                display(traceback.print_exc())  # どの行でエラーが発生したか表示

0it [00:00, ?it/s]

https://www.toshin-hensachi.com/?line=2&university_type=11&page=1&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=2&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=3&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=4&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=5&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=6&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=7&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=8&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=9&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=10&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=11&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=11&page=12&sort=deviation&direction=DESC

1it [00:19, 19.29s/it]

https://www.toshin-hensachi.com/?line=2&university_type=12&page=1&sort=deviation&direction=DESC

2it [00:20,  8.85s/it]

https://www.toshin-hensachi.com/?line=2&university_type=13&page=1&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=2&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=3&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=4&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=5&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=6&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=7&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=8&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=9&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=10&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=11&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=12&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=13&page=13&sort=deviation&direction=DESC

3it [00:42, 14.54s/it]

https://www.toshin-hensachi.com/?line=2&university_type=21&page=1&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=2&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=3&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=4&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=5&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=6&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=7&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=8&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=9&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=10&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=11&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=12&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=13&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=14&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=21&page=15&sort=deviation&direction=DESC

4it [01:08, 19.02s/it]

https://www.toshin-hensachi.com/?line=2&university_type=22&page=1&sort=deviation&direction=DESC

5it [01:09, 12.69s/it]

https://www.toshin-hensachi.com/?line=2&university_type=23&page=1&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=2&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=3&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=4&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=5&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=6&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=7&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=8&sort=deviation&direction=DESC
https://www.toshin-hensachi.com/?line=2&university_type=23&page=9&sort=deviation&direction=DESC

6it [01:24, 14.11s/it]

In [17]:
# データをデータフレームとして格納し、csv形式で保存する
df = pd.DataFrame(data_list)
df.to_csv("toshin_university_data.csv", index=True, encoding="utf-8-sig")

In [18]:
df

,大学名,学部,大学詳細ページ,偏差値,倍率情報,合格体験記,入試日程
0,東京大学,文科一類,http://www.toshin-daigaku.com/detail_lecture.p...,70,https://www.toshin.com/examinee/detail.php?id=19,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
1,東京大学,文科二類,http://www.toshin-daigaku.com/detail_lecture.p...,70,https://www.toshin.com/examinee/detail.php?id=19,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
2,東京大学,文科三類,http://www.toshin-daigaku.com/detail_lecture.p...,70,https://www.toshin.com/examinee/detail.php?id=19,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
3,京都大学,教育/教育科学(文系),http://www.toshin-daigaku.com/detail_lecture.p...,69,https://www.toshin.com/examinee/detail.php?id=42,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
4,京都大学,経済/経済経営(文系),http://www.toshin-daigaku.com/detail_lecture.p...,69,https://www.toshin.com/examinee/detail.php?id=42,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
...,...,...,...,...,...,...,...
2409,日本大学,生物資源/アグリサイエ（A1期）、食品開発（A1期）,http://www.toshin-daigaku.com/detail_lecture.p...,47,https://www.toshin.com/examinee/detail.php?id=142,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
2410,日本大学,生物資源/環境（A1期）,http://www.toshin-daigaku.com/detail_lecture.p...,45,https://www.toshin.com/examinee/detail.php?id=142,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
2411,北海学園大学,工/社会環境工／環境情,http://www.toshin-daigaku.com/detail_lecture.p...,44,https://www.toshin.com/examinee/detail.php?id=99,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
2412,日本獣医生命科学大学,応用生命/食品科学（第1回）,http://www.toshin-daigaku.com/detail_lecture.p...,43,https://www.toshin.com/examinee/detail.php?id=143,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...
2413,東海大学,工/応用化,http://www.toshin-daigaku.com/detail_lecture.p...,41,https://www.toshin.com/examinee/detail.php?id=133,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...

In [19]:
for url1 in df:
    print(url1)

大学名
学部
大学詳細ページ
偏差値
倍率情報
合格体験記
入試日程

In [ ]:
df = pd.read_csv("toshin_university_data.csv")
df.head(1)
for index in range(len(df)):
    print(df.iloc[index])

In [36]:
url="http://www.toshin-daigaku.com/detail_lecture.php?id=019"
html = urlopen(url).read()
soup = BeautifulSoup(html, "html.parser")

In [63]:
# 偏差値帯
deviation_min = soup.find("p", class_="deviation-min").text.strip()
deviation_max = soup.find("p", class_="deviation-max").text.strip()

In [72]:
intro_tables = soup.find_all("div", class_="undergraduate_block")
for intro_table in intro_tables:
    #^　学部と分野のデータ
    department = intro_table.find("h2").text.strip()
    lectures_list = intro_table.find("td", class_="lectures_list").text.strip()
    introductions =  intro_table.find_all("p", class_="introduction")
    introduction_list = []
    for introduction in introductions:
        introduction_list.append(introduction.text.strip())

In [77]:
intro_tables[2]

<div class="undergraduate_block" id="undergraduate_block-0-8216">
<h2>経済学部</h2>
<p class="headline"></p>
<table class="intro_table"><tr><th rowspan="2">経済学部</th><th>定員</th><th rowspan="2">学問分野</th><td class="lectures_list" rowspan="2">経済学 経営学 </td></tr><tr><td>340人</td></tr></table><p class="introduction">【特色】少人数教育を重視し、学部プラス1年で修士号を取得できるプログラムも設置。</p><p class="introduction">【進路】約1割が大学院へ進学。就職先は金融・保険業、学術研究・専門技術サービス業など。</p><table class="intro_table"><tr><th class="license">取得できる免許・資格</th><td>学芸員、教員免許（高-公）、司書教諭、司書</td></tr><tr><th class="license">所属キャンパス</th><td>本郷地区キャンパス（本郷キャンパス）</td></tr><tr><th class="license">学部と直結する大学院</th><td>経済学</td></tr></table> <h5><span>■</span>学科・コース・専修一覧</h5>
<table class="intro_table"><tr><th class="name">経済学科</th><td class="introduction">経済全体の水準や失業、物価上昇率、経済成長の決定要因に加え、経済状態をコントロールする政策について分析する。様々な資源の配分パターンがどのように決定されるか、また社会にとって望ましい所得分配を実現するための方法などについて具体的に考察する。</td></tr><tr><th class="name">経営学科</th><td class="introduction">企業や組織における経営活動に主眼を置く。企業経営に関わる様々な科目を軸に、経営管理や人事、商品開発などの実務、財務や資産の運用、調達に関する理論的方法とその実践について学ぶ。会計制度や企業経営の歴史に至るまで幅広く学ぶことができる。</td></tr><tr><th class="name">金融学科</th><td class="introduction">経済学や会計学の専門知識に基づく金融分野の理論を学ぶとともに、金融界の協力を得た実務教育も行われている。金融や経済、社会の仕組みについての深い理解を身につける。経済理論の知識に偏ることなく、戦略的構想力や思考能力を兼ね備えた人材を育成する。</td></tr></table> </div>

In [62]:
lectures_list

'言語学 歴史学 法学 政治学 経済学 社会学 数学 物理学 化学 生物学 応用生物学'

In [53]:
lectures_list

[<td class="lectures_list" rowspan="2">言語学 歴史学 法学 政治学 経済学 社会学 数学 物理学 化学 生物学 応用生物学 </td>,
 <td class="lectures_list" rowspan="2">法学 政治学 </td>,
 <td class="lectures_list" rowspan="2">経済学 経営学 </td>,
 <td class="lectures_list" rowspan="2">文学 言語学 哲学 心理学 歴史学 文化学 社会学 国際学 芸術理論 人間科学 </td>,
 <td class="lectures_list" rowspan="2">健康科学 教員養成 教育学 人間科学 </td>,
 <td class="lectures_list" rowspan="2">文学 言語学 歴史学 地理学 文化学 経済学 社会学 国際学 物理学 化学 エネルギー工学 健康科学 情報学 </td>,
 <td class="lectures_list" rowspan="2">化学 応用物理学 応用化学 機械工学 電気・電子工学 材料工学 土木・建築学 船舶・航空宇宙工学 応用生物学 環境学 情報学 </td>,
 <td class="lectures_list" rowspan="2">数学 物理学 化学 生物学 地学 エネルギー工学 環境学 情報学 </td>,
 <td class="lectures_list" rowspan="2">農学 獣医・畜産学 応用生物学 環境学 </td>,
 <td class="lectures_list" rowspan="2">薬学 </td>,
 <td class="lectures_list" rowspan="2">医学 </td>,
 <td class="lectures_list" rowspan="2">看護学 健康科学 </td>]

In [1]:
import pandas as pd

In [14]:
urls_df = pd.read_csv("toshin_university_data.csv")

In [16]:
urls_df.head(1)

,Unnamed: 0,大学名,学部,大学詳細ページ,偏差値,倍率情報,合格体験記,入試日程
0,0,東京大学,文科一類,http://www.toshin-daigaku.com/detail_lecture.p...,70,https://www.toshin.com/examinee/detail.php?id=19,https://www.toshin.com/taikenki/?univ_other%5B...,https://www.toshin.com/nyushi_info/schedule/?u...

In [20]:
url = urls_df.iat[0,3]
html = urlopen(url).read()  #^ スクレイピング
time.sleep(1)  # 1秒待つ
soup = BeautifulSoup(html, "html.parser")

In [22]:
url

'http://www.toshin-daigaku.com/detail_lecture.php?id=019'

In [21]:
soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>東京大学 入試情報｜大学案内｜東進ドットコム</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="大学案内,大学,情報,東進,受験,志望校,入試,予備校,塾,難易度,偏差値,東京大学" name="keywords"/>
<meta content="学部学科ごとの偏差値も掲載中！東進の大学案内。自分に合った志望校を探すのに役立つ情報が満載！大学の学部･学科紹介から偏差値、入試情報、就職状況や学費まで掲載。" name="description"/>
<link href="https://www.toshin.com/common_source/pc/css/global.css" rel="stylesheet"/> <link href="css/reset.css" rel="stylesheet" type="text/css"/>
<link href="css/style.css" rel="stylesheet" type="text/css"/>
<link href="css/site_global_header.css" rel="stylesheet" type="text/css"/>
<link href="css/detail_common.css" rel="stylesheet" type="text/css"/>
<link href="css/detail.css" rel="stylesheet" type="text/css"/>
<link href="css/detail_nav.css" rel="stylesheet" type="text/css"/>
<link href="css/detail_lecture.css" rel="stylesheet" type="text/css"/>
<link href="css/site_page_header.css" rel="stylesheet" type="text/css"/>
<link href="https://www.toshin.com/img/toshin32.ico" rel="icon"/>
<script defer="" src="assets/js/jquery-1.10.2.min.js" type="text/javascript"></script>
<script defer="" src="js/detail_nav.js" type="text/javascript"></script>
<script defer="" src="js/detail_lecture.js" type="text/javascript"></script>
<script async="" charset="utf-8" src="//www.toshin.com/js/tracking_code.js" type="text/javascript"></script></head>
<body id="detail">
<!-- <style>
    #global-header{
      background-image: none;
    }
  </style> -->
<!--ページ更新ボタンー START -->
<div class="reload-btn-wrap" id="reload-btn" onclick="window.location.reload(true); _gaq.push(['_trackEvent', 'page-reload', 'pc', 'toshin-reload-btn'+'_'+location.href.split(/\?|\#/)[0]]);">
<div class="reload-btn">
<img alt="ページを更新する" class="reload-icon" src="https://www.toshin.com/resources/img/reload/reload-icon.png"/>
<span class="reload-txt">ページを更新する</span>
</div>
</div>
<style>
  .reload-btn-wrap {
    margin: 0 auto;
    position: relative;
    text-align: right;
    z-index: 1000000000;
  }

  .reload-btn {
    align-items: center;
    background: rgba(255, 255, 255, .8);
    border: solid 2px #4d4d4d;
    border-radius: 5px;
    box-shadow: 2px 2px 2px rgba(0, 0, 0, .3);
    cursor: pointer;
    display: inline-flex;
    margin: 5px 0;
    padding: 2px 5px;
    position: absolute;
    left: calc(1000px + (100% - 1000px)/2);
    top: 5px;
  }

  @media screen and (max-width: 1371px) {
    .reload-btn {
      right: 0;
      left: auto;
    }
  }

  .reload-btn:hover {
    opacity: .7;
  }

  .reload-btn .reload-icon {
    padding-left: 3px;
    width: 20px;
  }

  .reload-txt {
    color: #4d4d4d;
    font-family: 'Lato', 'Noto Sans JP', '游ゴシック Medium', '游ゴシック体', 'Yu Gothic Medium', 'YuGothic', 'ヒラギノ角ゴ ProN', 'Hiragino Kaku Gothic ProN', 'メイリオ', 'Meiryo', 'ＭＳ Ｐゴシック', 'MS PGothic', 'sans-serif';
    font-size: 16px;
    margin-left: 8px;
  }
</style>
<script>
  window.addEventListener('load', function() {
    var reloadBtn = document.getElementById('reload-btn');
    setTimeout(function() {
      reloadBtn.animate([{
        opacity: '1'
      }, {
        opacity: '0'
      }], 500);
    }, 5000);
    setTimeout(function() {
      reloadBtn.style.display = 'none';
    }, 5500);
  });
  window.addEventListener('scroll', function() {
    var reloadBtn = document.getElementById('reload-btn');
    reloadBtn.animate([{
      opacity: '1'
    }, {
      opacity: '0'
    }], 500);
    setTimeout(function() {
      reloadBtn.style.display = 'none';
    }, 500);
  });
</script>
<!--ページ更新ボタンー END -->
<header id="global-header">
<!--グローバルヘッダー START -->
<div class="global-header-inner">
<div class="toshin-logo">
<a href="https://www.toshin.com/">
<img alt="Toshin.com" src="https://www.toshin.com/common_source/pc/img/toshin_logo.png"/>
<span>大学受験(大学入試)対策の塾・予備校なら東進</span>
</a>
</div>
<!-- box-banner -->
<div class="global-header-top01">
<a href="https://www.toshin.com/jisseki/" onclick="_gaq.push(['_trackEvent', 'jisseki2022', 'pc', 'header'+'_'+location.href.split(/\?|\#/)[0]]);">
<img alt="東進現役合格実績" src="https://www.toshin.com/resources/banners/jisseki/365_45.jpg"/>
</a>
</div>
<!-- <div class="global-header-top01">
      <a href="https://www.toshin.com/hantei_sys/" onClick="_gaq.push(['_trackEvent', 'global-header', 'pc', 'pc_global-header_hantei_sys'+'_'+location.href.split(/\?|\#/)[0]]);">
        <img src="https://www.toshin.com/resources/banners/hantei_sys/365_45.jpg" alt="合否判定システム">
      </a>
    </div> -->
<!-- box-sns -->
<!-- <div class="global-header-top02">
      <div class="global-header-sns-twitter">
                <a href="https://twitter.com/share" class="twitter-share-button" data-url="https://www.toshin.com/index.php" data-text="" data-count="horizontal" data-lang="ja"><img src="https://www.toshin.com/common_source/pc/img/twitter_btn.png" class="global-twitter-img"></a>
      </div>
      <div class="global-header-sns-facebook">
        <iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.toshin.com%2F&width=72&layout=button&action=like&size=small&show_faces=false&share=false&height=30&appId" width="72" height="30" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
      </div>
    </div> -->
<!-- box-search -->
<div class="global-header-top03">
<div class="global-header-utility">
<ul>
<li><a href="https://www.toitsutest.com/" rel="noopener" target="_blank">全国統一ﾃｽﾄ</a></li>
<li><a href="https://www.toshin.com/nagase/">企業案内</a></li>
<li><a href="https://www.toshin.com/nagase/recruit/">採用情報</a></li>
<li><a href="https://www.toshin.com/sitemap/">ｻｲﾄﾏｯﾌﾟ</a></li>
<li><a href="https://www.toshin.com/news_release/" rel="noopener" target="_blank">ﾆｭｰｽﾘﾘｰｽ</a></li>
</ul>
</div>
<div class="global-header-search">
<!-- 検索ボックス -->
<div class="cse-branding-bottom">
<div class="cse-branding-form">
<form action="https://www.toshin.com/search/search_result.php" id="cse-search-box">
<div class="cse-search-input">
<input name="cx" type="hidden" value="partner-pub-0636460989826629:6666848261"/>
<input name="cof" type="hidden" value="FORID:10"/>
<input name="ie" type="hidden" value="UTF-8"/>
<input id="q" name="q" placeholder=" 校舎名、イベント名で検索" size="17" type="text"/>
<input name="sa" type="submit" value="検索"/>
</div>
</form>
<div class="cse-branding-logo">
<img alt="Google" src="https://www.google.com/images/poweredby_transparent/poweredby_FFFFFF.gif"/>
</div>
</div>
</div>
</div>
</div>
</div>
<!--グローバルヘッダー END -->
<!--グローバルメニュー START-->
<nav class="global-header-menu">
<div class="global-header-menu-inner">
<div class="menuItem" onmouseout="document.getElementById('hsPullDown').style.display='none'" onmouseover="document.getElementById('hsPullDown').style.display='block'">
<a href="https://www.toshin.com/hs/">
<img alt="東進ハイスクール" src="https://www.toshin.com/common_source/pc/img/01.png"/>
</a>
<div class="pullDown" id="hsPullDown">
<ul class="menuItem-link">
<li><a href="https://www.toshin.com/hs/">東進ハイスクール</a></li>
</ul>
<ul class="menuItem-link menuItem-link-iconMiddle">
<li><a href="https://www.toshin.com/teacher/">講師紹介</a></li>
<li><a href="https://www.toshin.com/courses/">講座案内</a></li>
<li><a href="https://www.toshin.com/hs/map/">校舎案内</a></li>
<li><a href="https://www.toshin-moshi.com/">東進模試</a></li>
<li><a href="https://www.toshin.com/jisseki/">合格実績</a></li>
<li><a href="https://www.toshin.com/taikenki/">合格体験記</a></li>
<li><a href="https://www.toshin.com/system/">第一志望合格のために</a></li>
</ul>
<div class="menuItem-link-request">
<a href="https://www.toshin.com/sform/shiryo-seikyu/input?form_action=shiryo&amp;desire=all">
<img alt="資料・入学案内請求" src="https://www.toshin.com/common_source/pc/img/shiryo_seikyu.jpg"/>
</a>
</div>
</div>
</div>
<div class="menuItem" onmouseout="document.getElementById('esPullDown').style.display='none'" onmouseover="document.getElementById('esPullDown').style.display='block'">
<a href="https://www.toshin.com/es/">
<img alt="東進衛星予備校" src="https://www.toshin.com/common_source/pc/img/02.png"/>
</a>
<div class="pullDown" id="esPullDown">
<ul class="menuItem-link">
<li><a href="https://www.toshin.com/es/">東進衛星予備校</a></li>
</ul>
<ul class="menuItem-link menuItem-link-iconMiddle">
<li><a href="https://www.toshin.com/teacher/">講師紹介</a></li>
<li><a href="https://www.toshin.com/courses/">講座案内</a></li>
<li><a href="https://www.toshin.com/es/map/">校舎案内</a></li>
<li><a href="https://www.toshin.com/exams/">東進模試</a></li>
<li><a href="https://www.toshin.com/jisseki/">合格実績</a></li>
<li><a href="https://www.toshin.com/taikenki/">合格体験記</a></li>
</ul>
<div class="menuItem-link-request">
<a href="https://www.toshin.com/sform/shiryo-seikyu/input?form_action=shiryo&amp;desire=all">
<img alt="資料・入学案内請求" src="https://www.toshin.com/common_source/pc/img/shiryo_seikyu.jpg"/>
</a>
</div>
</div>
</div>
<div class="menuItem">
<a href="https://www.toshin.com/jisseki/">
<img alt="合格実績" src="https://www.toshin.com/common_source/pc/img/04.png"/>
</a>
</div>
<div class="menuItem">
<a href="https://www.toshin.com/map/?top=1">
<img alt="校舎案内" src="https://www.toshin.com/common_source/pc/img/05.png"/>
</a>
</div>
<div class="menuItem" onmouseout="document.getElementById('examsPullDown').style.display='none'" onmouseover="document.getElementById('examsPullDown').style.display='block'">
<a href="https://www.toshin-moshi.com/">
<img alt="東進模試" src="https://www.toshin.com/common_source/pc/img/06.png"/>
</a>
<!-- <div id="examsPullDown" class="pullDown">
          <ul class="menuItem-link">
            <li><a href="https://www.toshin-moshi.com/">東進模試 トップページ</a></li>
          </ul>
          <ul class="menuItem-link menuItem-link-iconMiddle">
            <li><a href="https://www.toshin.com/kyotsutest_doujitsu/">共通テスト同日体験受験</a></li>
            <li><a href="https://www.toshin-moshi.com/kyotsu/">共通テスト本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/nankan_level/">早慶上理・難関国公立大模試</a></li>
            <li><a href="https://www.toshin-moshi.com/yumei_level/">全国有名国公私大模試</a></li>
            <li><a href="https://www.toshin-moshi.com/todai_level/">東大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/todai_level_h2/">高2東大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/kyodai_level/">京大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/hokudai_honban/">北大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/tohokudai_honban/">東北大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/meidai_honban/">名大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/handai_honban/">阪大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/kyudai_honban">九大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/hitotsubashi_level/">一橋大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/toukoudai_level">東工大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/todai_doujitsu/">東大入試同日体験受験</a></li>
            <li><a href="https://www.toshin-moshi.com/basic_ex/">大学合格基礎力判定テスト</a></li>
            <li><a href="https://www.toshin-moshi.com/center_high/">高校レベル記述模試</a></li>
            <li><a href="https://www.toitsutest-koukou.com/">全国統一高校生テスト</a></li>
            <li><a href="https://www.toitsutest-chugaku.com/">全国統一中学生テスト</a></li>
            <li><a href="https://www.toshin-moshi.com/chibadai_level/">千葉大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/koubedai_level/">神戸大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/hiroshimadai_level/">広島大本番レベル模試</a></li>
            <li><a href="https://www.toshin-moshi.com/igakubu">医学部82大学判定テスト</a></li>
            <li><a href="https://www.toshin-moshi.com/chugaku_hantei">中学学力判定テスト</a></li>
            <li><a href="https://www.toshin-moshi.com/meidai_doujitsu">名大入試同日体験受験</a></li>
            <li><a href="https://www.toshin-moshi.com/tohokudai_doujitsu">東北大入試同日体験受験</a></li>
            <li><a href="https://www.toshin-moshi.com/information1_taiken/">大学入学共通テスト「情報Ⅰ」体験模試</a></li>
          </ul>
        </div> -->
</div>
<div class="menuItem">
<div><a href="https://www.toshin-kakomon.com/"><img alt="過去問データベース" src="https://www.toshin.com/common_source/pc/img/07.png"/></a></div>
</div>
<div class="menuItem" onmouseout="document.getElementById('posPullDown').style.display='none'" onmouseover="document.getElementById('posPullDown').style.display='block'">
<a href="https://www.toshin.com/pos/" onclick="_gaq.push(['_trackEvent', 'global-header', 'pc', 'pos'+location.href.split(/\?|\#/)[0]]);">
<img alt="東進学力POS" src="https://www.toshin.com/common_source/pc/img/08.png"/>
</a>
<div class="pullDown" id="posPullDown">
<ul class="menuItem-link">
<li>高校生対象</li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://www.toshin.com/pos/">東進ハイスクール<br/>東進衛星予備校<br/>東進個別</a></li>
</ul>
<ul class="menuItem-link">
<li>中学生対象</li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://pos.toshin.com/SSO1/TJ/SSOLogin/StudentLogin.aspx">東進ハイスクール<br/>東進中学NET</a></li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://pos.toshin.com/SSO21/TO/SSOLogin/SSOLogin/">東進オンライン学校</a></li>
</ul>
<ul class="menuItem-link">
<li>小学生・中学生対象</li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://pos.toshin.com/SSO21/TO/SSOLogin/SSOLogin/">東進オンライン学校</a></li>
</ul>
<ul class="menuItem-link">
<li>大学生対象</li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://pos.toshin.com/SSO21/BIZ/SSOLogin/SSOLogin">東進ビジネススクール<br/>大学生向け東進学力POS</a></li>
</ul>
<ul class="menuItem-link">
<li>社会人対象</li>
</ul>
<ul class="menuItem-link menuItem-link-iconTop">
<li><a href="https://pos.toshin.com/SSO21/BIZ/SSOLogin/SSOLogin">東進ビジネススクール<br/>社会人向け東進学力POS</a></li>
</ul>
</div>
</div>
<div class="menuItem">
<a href="https://pos.toshin.com/PSSO/PSSO" onclick="_gaq.push(['_trackEvent', 'global-header', 'pc', 'mypage'+location.href.split(/\?|\#/)[0]]);">
<img alt="マイページ" src="https://www.toshin.com/common_source/pc/img/11.png"/>
</a>
</div>
<div class="menuItem">
<a href="https://www.toshin.com/sform/shiryo-seikyu/input?form_action=shiryo&amp;desire=all">
<img alt="資料請求" src="https://www.toshin.com/common_source/pc/img/09.png"/>
</a>
</div>
<div class="menuItem">
<a href="https://www.toshin.com/sform/shiryo-seikyu/?form_action=nyugaku">
<img alt="入学受付" src="https://www.toshin.com/common_source/pc/img/10.png"/>
</a>
</div>
</div>
</nav>
<!--グローバルメニュー END-->
</header>
<div id="site_contents">
<div id="site_contents-wrapper">
<div id="site-global-header">
<div class="wrapper">
<div class="logo">
<a href="./"><img alt="大学案内" src="img/logo_for_site_global_header.png"/></a>
</div>
<h1><p class="site-catch-copy">東進が厳選した全国の大学情報を掲載！各大学の学部・学科の偏差値など志望校選びに役立つ情報が満載！</p></h1>
</div>
</div>
<div class="clear"></div>
<div class="univ-header">
<div id="inc_univ_header">
<img src="./inc_univ/019/img/toudai.png"/>
</div> </div>
<div class="clear"></div>
<div class="clear"></div>
<div id="page_header">
<h1>
    東京大学    <span>学部・学科情報</span>
</h1>
<p class="tag">
        国立    東京都
  <div class="deviation-content">
<p class="deviation-header">偏差値</p>
<div class="deviation-num-box">
<p class="deviation-min">70～</p>
<p class="deviation-max">74</p>
</div>
</div>
<!-- 東進模試リンク設置 変数はlib_common.phpで定義 $EXAM_LINK-->
<div class="exam-link-content">
<p class="exam-message">東京大学を<br/>志望する方におすすめの模試</p>
<a class="link-exams" href="https://www.toshin-moshi.com/kyotsu/" target="_blank">
<div class="exam-link-honban"><img class="exam-image" decoding="async" loading="lazy" src="https://www.toshin.com/resources/banners/daigaku/doujitsu_tyokkin/kyotsu.jpg"/><i class="fas fa-angle-right"></i></div>
</a>
<!-- <a target="_blank" class="link-exams" href="https://www.toshin-moshi.com/recent/"><div class="exam-link-recent"><img src="https://www.toshin.com/resources/banners/daigaku/doujitsu_tyokkin/recent.jpg" class="exam-image" loading="lazy" decoding="async"><i class="fas fa-angle-right"></i></div></a> -->
<!-- 本番レベル模試 -->
<a class="link-exams" href="https://www.toshin.com/exams/todai_level" target="_blank">
<div class="exam-link-honban exam-link-todai">
<img class="exam-image" decoding="async" loading="lazy" src="https://www.toshin.com/resources/banners/daigaku/todai.jpg"/>
<i class="fas fa-angle-right"></i>
</div>
</a>
<a class="link-exams" href="https://www.toshin.com/exams/todai_level_h2" target="_blank">
<div class="exam-link-honban exam-link-todai">
<img class="exam-image" decoding="async" loading="lazy" src="https://www.toshin.com/resources/banners/daigaku/kounitodai.jpg"/>
<i class="fas fa-angle-right"></i>
</div>
</a>
<!-- 同日・直近日体験受験 -->
<!-- <a target="_blank" class="link-exams" href="https://www.toshin.com/exams/todai_level_h2">
              <div class="exam-link-honban exam-link-todai">
                <img src="https://www.toshin.com/resources/banners/daigaku/kounitodai.jpg" class="exam-image" loading="lazy" decoding="async">
                <i class="fas fa-angle-right"></i>
              </div>
            </a> -->
</div>
<!-- 難関早慶上理 -->
</p>
</div> <div id="wrapper">
<div id="contents">
<div id="main">
<div id="detail_nav">
<ul>
<li><a class="nav_list" href="detail.php?id=019">基本情報</a></li>
<li><a class="nav_list" href="detail_lecture.php?id=019">学部・学科</a></li>
<li><a class="nav_list" href="detail_job.php?id=019">進路・就職状況</a></li>
<li><a class="nav_list" href="detail_exam.php?id=019">入試情報</a></li>
<a href="https://www.toshin-hensachi.com/">
<p>大学入試偏差値<br/>ランキング一覧はこちら</p>
</a>
<!--           <li><a href="detail_voice.php?id=019" class="nav_list">先輩の声</a></li>
     -->
</ul>
</div>
<div id="detail_fixed_header">
<div class="wrapper">
<div class="page_navigation">
<div class="univ_name page_title">東京大学</div>
<ul class="link_list">
<li><a class="nav_list" href="detail.php?id=019">基本情報</a></li>
<li><a class="nav_list" href="detail_lecture.php?id=019">学部・学科</a></li>
<li><a class="nav_list" href="detail_job.php?id=019">進路・就職状況</a></li>
<li><a class="nav_list" href="detail_exam.php?id=019">入試情報</a></li>
<!--                   <li><a href="detail_voice.php?id=019" class="nav_list">先輩の声</a></li>
         -->
</ul>
</div>
</div>
</div> <div id="main_column">
<div id="lecture">
<h2>目次</h2>
<div class="academic_group_block" id="academic_group_block-0">
<h4><span>■</span>学部の選択をして下さい。</h4>
<div class="undergraduate_btn" id="undergraduate_btn-0-8214">
                        教養学部（前期課程）                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8215">
                        法学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8216">
                        経済学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8217">
                        文学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8218">
                        教育学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8219">
                        教養学部（後期課程）                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8220">
                        工学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8221">
                        理学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8222">
                        農学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8223">
                        薬学部                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8224">
                        医学部（医）                      </div>
<div class="undergraduate_btn" id="undergraduate_btn-0-8225">